server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: http:localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"