server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        dashboard: http://localhost:8080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true